name: Filpkart - linter

on: push

jobs:
super-lint:
name1: Lint Code_base
runs on: ubuntu-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2
    with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       
    xml-file: 'pom.xml'
  - name: Run Super-Linter
    uses: github/super-linter@v3
    env:
      DEFAULT_BRANCH: main
      
